# Generated by Django 3.2.25 on 2025-05-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stressapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('exercise_hours_per_week', models.FloatField()),
                ('stress_level', models.FloatField()),
                ('sedentary_hours_per_day', models.FloatField()),
                ('bmi', models.FloatField()),
                ('sleep_hours_per_day', models.FloatField()),
                ('hrv', models.FloatField()),
                ('eda', models.FloatField()),
                ('skin_temperature', models.FloatField()),
                ('respiration_rate', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('diet', models.CharField(max_length=10)),
                ('prediction_result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
