# Generated by Django 3.2.25 on 2025-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0002_stressrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressrecord',
            name='diet',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Unhealthy', 'Unhealthy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stressrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stressrecord',
            name='prediction_result',
            field=models.CharField(max_length=10),
        ),
    ]
